name: frontend
description: "نعمرها صح - تطبيق البلاغات الهندسية والعنونة الرقمية"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Map & Location
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Storage & Offline
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.3

  # Networking
  dio: ^5.8.0

  # Google Fonts (Arabic support)
  google_fonts: ^6.2.1

  # Icons
  iconsax: ^0.0.8

  # Image Picking & Permissions
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpeg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpeg
